### ISSUE TITLE
用户界面显示自己当月消耗的总流量

### ISSUE THREAD

**Issue by gaoyifan** [zzh1996/lug-vpn-web#14]
(Moved From GitLab)

**Comment by gaoyifan** [comment]
参考SQL：

```
CREATE OR REPLACE VIEW radius.monthtraffic AS select radius.radacct.username AS UserName,(sum((radius.radacct.acctinputoctets + radius.radacct.acctoutputoctets)) / 1048576) AS TrafficSum from radius.radacct where ((month(radius.radacct.acctstarttime) = month(now())) and (year(radius.radacct.acctstarttime) = year(now()))) group by radius.radacct.username order by (sum((radius.radacct.acctinputoctets + radius.radacct.acctoutputoctets)) / 1048576)
```

**Comment by zzh1996** [comment]
last month traffic
`CREATE OR REPLACE VIEW radius.lastmonthtraffic AS select radius.radacct.username AS UserName,(sum((radius.radacct.acctinputoctets + radius.radacct.acctoutputoctets)) / 1048576) AS TrafficSum from radius.radacct where ((month(radius.radacct.acctstarttime) = month(date_sub(now(),interval 1 month))) and (year(radius.radacct.acctstarttime) = year(date_sub(now(),interval 1 month)))) group by radius.radacct.username order by (sum((radius.radacct.acctinputoctets + radius.radacct.acctoutputoctets)) / 1048576);
`
