### ISSUE TITLE
IKEv2连接无记录显示

### ISSUE THREAD

**Issue by liyishuai** [zzh1996/lug-vpn-web#21]
设备：iPhone 5s (A1453)
操作系统：iOS 9.3.2 (13F69)
网络环境：电信PPPoE、路由器NAT

相同环境下PPTP连接有记录显示。

**Comment by gaoyifan** [comment]
fixed
https://github.com/gaoyifan/docker-strongswan/commit/c00dab27510d7215c5491fac6530a728a8489c63
