### ISSUE TITLE
新用户登录时，旧cookie不会失效

### ISSUE THREAD

**Issue by gaoyifan** [zzh1996/lug-vpn-web#23]
问题描述：
1. 使用A账号登录网站，不要点击logout
2. 重新访问/login，使用B账号登录网站，呈现的信息仍然是A账号的。

修复建议
Method A:
如果在/login页面检测到有效cookie，直接跳转至/

Method B:
新账号登录时，旧cookie标记失效

**Comment by zzh1996** [comment]
问题无法重现，我在登录状态访问login直接跳转回首页。
2016-6-28我的一次commit在/app/views.py增加了

```
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
```

以上几行代码，就是判断已登录时再次访问登录直接跳转到首页。
