### ISSUE TITLE
账号的过期

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [zzh1996/lug-vpn-web#27]
在radcheck里维护一项 attribure为'Expiration'的 value为日期（[格式在此](http://networkradius.com/doc/3.0.10/raddb/mods-available/expiration.html)）的记录。
通过username来标明某用户会在此时间后过期。
为了方便只写日期不写时间也可以，如 '7 Sep 2016'就使提交此issue的时间无法通过验证。
前端添加申请时限，默认2个月之类的。后端就可以在申请的时候一次insert两条，一条Cleartext-Password，一条Expiration。
变回永久是: `delete from radcheck where username='a@b.c' and attribute='Expiration';`
续期通过把已有的Expiration的value改变(当前时间+2个月)即可。
参考

``` python
import datetime
(datetime.date.today()+datetime.timedelta(days=60)).strftime('%d %b %Y')
```

**Comment by zzh1996** [comment]
过些天我把这个功能做了

**Comment by zzh1996** [comment]
数据库直接执行的操作：
```
alter table user add expiration date default null;
alter table user add renewing tinyint(1) not null default 0;
update user set expiration='2017-08-31';
insert into radcheck (username,attribute,op,value) select email,'Expiration',':=','31 Aug 2017' from user where (select count(*) from radcheck where radcheck.username=user.email)>0;

```
