### ISSUE TITLE
如何申请增加代理网址？

### ISSUE THREAD

**Issue by AStupidBear** [zzh1996/lug-vpn-web#31]
记得以前有个地址提交，现在忘了

**Comment by gaoyifan** [comment]
VPN可以访问所有地址，无需申请

**Comment by AStupidBear** [comment]
我指的是light.ustc.edu.cn那个

**Comment by gaoyifan** [comment]
**light.ustclug.org** 在[这里](https://git.ustclug.org/lug-light/accelerate-list)申请加速域名变更

**Comment by gaoyifan** [comment]
关于light的疑问请致信light(AT) ustclug.org
