### ISSUE TITLE
应对安全漏洞

### ISSUE THREAD

**Issue by SmartHypercube** [zzh1996/lug-vpn-web#48]
https://github.com/ustclug/lug-vpn-web/network/alerts
需要尝试升级一些依赖

**Comment by taoky** [comment]
> https://github.com/ustclug/lug-vpn-web/network/alerts
> 需要尝试升级一些依赖

现在 GitHub 可以设置发现 CVE 的时候让 dependabot 自动发（仅内部可见的）修复 PR 了。可以看一下那个设置选项。

https://help.github.com/en/articles/configuring-automated-security-fixes

**Comment by SmartHypercube** [comment]
cool！居然还能自动修
不过目前这个项目看起来并没有产生安全警告呀

**Comment by taoky** [comment]
> cool！居然还能自动修 不过目前这个项目看起来并没有产生安全警告呀
> […](#)
> On Thu, Jun 13, 2019 at 12:14 AM taoky ***@***.***> wrote: https://github.com/ustclug/lug-vpn-web/network/alerts 需要尝试升级一些依赖 现在 GitHub 可以设置发现 CVE 的时候让 dependabot 自动发（仅内部可见的）修复 PR 了。可以看一下那个设置选项。 https://help.github.com/en/articles/configuring-automated-security-fixes — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

我现在开一下那个自动修复的选项试试，应该下次我们用到的组件有 CVE 的时候我们就会收到一个只有我们自己可见的 PR。
